name: rickandmorty
description: "An application on Flutter that downloads a list of characters from the animated series \"Rick and Morty\" from a public API. The app allows you to add characters to favorites and provides offline access to data."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  svg_flutter: ^0.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg_pictures/randm_pic.svg

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf